local M = {}

-- Change this to switch pickers: "mini.pick", "fzf-lua", "telescope", "snacks.picker"
M.picker = "fzf-lua"

M.get_plugin_spec = function()
	-- Plugins are now loaded separately in plugins/init.lua
	return {}
end

M.get_mappings = function()
	local map = vim.keymap.set
	if M.picker == "mini.pick" then
		map("n", "<leader>fh", function()
			require("mini.pick").builtin.help()
		end, { desc = "[F]ind [H]elp" })
		map("n", "<leader>fk", function()
			require("mini.pick").builtin.keymaps()
		end, { desc = "[F]ind [K]eymaps" })
		map("n", "<leader>ff", function()
			require("mini.pick").builtin.files()
		end, { desc = "[F]ind [F]iles" })
		map("n", "<leader>fs", function()
			require("mini.pick").builtin.builtin()
		end, { desc = "[F]ind [S]elect Picker" })
		map("n", "<leader>fw", function()
			require("mini.pick").builtin.grep()
		end, { desc = "[F]ind current [W]ord" })
		map("n", "<leader>fg", function()
			require("mini.pick").builtin.grep_live()
		end, { desc = "[F]ind by [G]rep" })
		-- map('n', '<leader>fd', function() require('mini.pick').builtin.diagnostics() end, { desc = '[F]ind [D]iagnostics' }) -- Not available in mini.pick
		map("n", "<leader>fr", function()
			require("mini.pick").builtin.resume()
		end, { desc = "[F]ind [R]esume" })
		map("n", "<leader>f.", function()
			require("mini.pick").builtin.oldfiles()
		end, { desc = '[F]ind Recent Files ("." for repeat)' })
		map("n", "<leader><leader>", function()
			require("mini.pick").builtin.buffers()
		end, { desc = "[ ] Find existing buffers" })
		map("n", "<leader>f/", function()
			require("mini.pick").builtin.grep({ pattern = vim.fn.input("Grep > ") })
		end, { desc = "[/] Fuzzily search in current buffer" })
		map("n", "<leader>f/", function()
			require("mini.pick").builtin.grep_live()
		end, { desc = "[F]ind [/] in Open Files" })
		map("n", "<leader>fn", function()
			require("mini.pick").builtin.files({ cwd = vim.fn.stdpath("config") })
		end, { desc = "[F]ind [N]eovim files" })
	elseif M.picker == "fzf-lua" then
		map("n", "<leader>fh", function()
			require("fzf-lua").help_tags()
		end, { desc = "[F]ind [H]elp" })
		map("n", "<leader>fk", function()
			require("fzf-lua").keymaps()
		end, { desc = "[F]ind [K]eymaps" })
		map("n", "<leader>ff", function()
			require("fzf-lua").files()
		end, { desc = "[F]ind [F]iles" })
		map("n", "<leader>fs", function()
			require("fzf-lua").builtin()
		end, { desc = "[F]ind [S]elect FZF" })
		map("n", "<leader>fw", function()
			require("fzf-lua").grep_cword()
		end, { desc = "[F]ind current [W]ord" })
		map("n", "<leader>fg", function()
			require("fzf-lua").live_grep()
		end, { desc = "[F]ind by [G]rep" })
		map("n", "<leader>fd", function()
			require("fzf-lua").diagnostics_document()
		end, { desc = "[F]ind [D]iagnostics" })
		map("n", "<leader>fr", function()
			require("fzf-lua").resume()
		end, { desc = "[F]ind [R]esume" })
		map("n", "<leader>f.", function()
			require("fzf-lua").oldfiles()
		end, { desc = '[F]ind Recent Files ("." for repeat)' })
		map("n", "<leader><leader>", function()
			require("fzf-lua").buffers()
		end, { desc = "[ ] Find existing buffers" })
		map("n", "<leader>f/", function()
			require("fzf-lua").grep_curbuf()
		end, { desc = "[/] Fuzzily search in current buffer" })
		map("n", "<leader>f/", function()
			require("fzf-lua").live_grep_resume()
		end, { desc = "[F]ind [/] in Open Files" })
		map("n", "<leader>fn", function()
			require("fzf-lua").files({ cwd = vim.fn.stdpath("config") })
		end, { desc = "[F]ind [N]eovim files" })
	elseif M.picker == "telescope" then
		map("n", "<leader>fh", function()
			require("telescope.builtin").help_tags()
		end, { desc = "[F]ind [H]elp" })
		map("n", "<leader>fk", function()
			require("telescope.builtin").keymaps()
		end, { desc = "[F]ind [K]eymaps" })
		map("n", "<leader>ff", function()
			require("telescope.builtin").find_files()
		end, { desc = "[F]ind [F]iles" })
		map("n", "<leader>fs", function()
			require("telescope.builtin").builtin()
		end, { desc = "[F]ind [S]elect Telescope" })
		map("n", "<leader>fw", function()
			require("telescope.builtin").grep_string()
		end, { desc = "[F]ind current [W]ord" })
		map("n", "<leader>fg", function()
			require("telescope.builtin").live_grep()
		end, { desc = "[F]ind by [G]rep" })
		map("n", "<leader>fd", function()
			require("telescope.builtin").diagnostics()
		end, { desc = "[F]ind [D]iagnostics" })
		map("n", "<leader>fr", function()
			require("telescope.builtin").resume()
		end, { desc = "[F]ind [R]esume" })
		map("n", "<leader>f.", function()
			require("telescope.builtin").oldfiles()
		end, { desc = '[F]ind Recent Files ("." for repeat)' })
		map("n", "<leader><leader>", function()
			require("telescope.builtin").buffers()
		end, { desc = "[ ] Find existing buffers" })
		map("n", "<leader>f/", function()
			require("telescope.builtin").current_buffer_fuzzy_find(require("telescope.themes").get_dropdown({
				winblend = 10,
				previewer = false,
			}))
		end, { desc = "[/] Fuzzily search in current buffer" })
		map("n", "<leader>f/", function()
			require("telescope.builtin").live_grep({
				grep_open_files = true,
				prompt_title = "Live Grep in Open Files",
			})
		end, { desc = "[F]ind [/] in Open Files" })
		map("n", "<leader>fn", function()
			require("telescope.builtin").find_files({ cwd = vim.fn.stdpath("config") })
		end, { desc = "[F]ind [N]eovim files" })
	elseif M.picker == "snacks.picker" then
		map("n", "<leader>fh", function()
			require("snacks").picker.help()
		end, { desc = "[F]ind [H]elp" })
		-- Add more as needed
	end
end

return M
